name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.23']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
        
    - name: Get dependencies (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
      if: ${{ runner.os == 'Linux' }}
    
    - name: Tests
      run: go test -tags test ./...
    
    - name: Update coverage
      run: |
        go test -tags test -covermode=atomic -coverprofile=coverage.out ./...
      if: ${{ runner.os == 'Linux' && matrix.go-version == '1.23' }}


